
CREATE TABLE sid3.kunjungan_anc_lab_test (
    first_name character varying(75),
    last_name character varying(75),
    birth_date character varying(75),
    event_id character varying(75) UNIQUE,
    document_id character varying(75),
    base_entity_id character varying(75),
    location_id character varying(75),
    date_created timestamp without time zone,
    event_date timestamp without time zone,
    clientversionsubmissiondate timestamp with time zone,
    serverversionsubmissiondate timestamp with time zone,
    provider_id character varying(75),
    laboratoriumguladarah text,
    treatmentthalasemiatxt text,
    -- regdate text,
    lokasiperiksa text,
    treatmentanemiatxt text,
    treatmentproturintxt text,
    laboratoriumperiksahbanemia text,
    laboratoriumproteinuria text,
    cityvillage text,
    -- subvillage text,
    treatmentdiabetestxt text,
    highriskpregnancyanemia text,
    -- submissiondate text,
    -- village text,
    -- today text,
    -- existinglocation text,
    referencedate text,
    laboratoriumthalasemia text,
    treatmenthbsagtxt text,
    lokasiperiksaother text,
    laboratoriumperiksahbhasil text,
    treatmentsifilistxt text,
    laboratoriumhbsag text,
    -- registrationdate text,
    ancid text,
    address1 text,
    laboratoriumsifilis text,
    highriskpregnancydiabetes text
);
