
CREATE TABLE sid_v2.kunjungan_anc (
    first_name character varying(75),
    last_name character varying(75),
    birth_date character varying(75),
    event_id character varying(75) UNIQUE,
    document_id character varying(75),
    base_entity_id character varying(75),
    location_id character varying(75),
    date_created timestamp without time zone,
    event_date timestamp without time zone,
    clientversionsubmissiondate timestamp with time zone,
    serverversionsubmissiondate timestamp with time zone,
    provider_id character varying(75),
    keadaanibusaatpulang text,
    province text,
    ancke text,
    -- lilacm text,
    jumlahjanin text,
    -- (pelayanancatatbukukia) text,
    -- (dusun) text,
    -- (tddiastolik) text,
    reflekspatelaibu text,
    taksiranberatjanin text,
    -- (referencedate) text,
    pelayananfe text,
    lainlain text,
    dirujuk text,
    -- kabupaten text,
    lokasiperiksa text,
    -- nomortelponhp text,
    trimesterke text,
    djj text,
    ancid text,
    highriskpregnancypih text,
    keterangan text,
    highrisklabourfetusmalpresentation text,
    district text,
    address1 text,
    nomortelpon text,
    caramasuktempatpelayanan text,
    bbkg text,
    persentasijanin text,
    highriskpregnancyproteinenergymalnutrition text,
    -- (today) text,
    hiddenancke text,
    cityvillage text,
    -- (tanggalhpht) text,
    statusgiziibu text,
    -- (jumlahfe) text,
    -- (dirujukkel) text,
    dirujukke text,
    -- registrationdate text,
    -- (village) text,
    usiaklinis text,
    anamnesisibu text,
    -- (kepalaterhadapjaninpap) text,
    pelayananinjeksitt text,
    kunjunganke text,
    statusimunisasitt text,
    -- (regdate) text,
    subdistrict text,
    -- (kecamatan) text,
    -- (desa) text,
    lokasiperiksaother text,
    -- (hpht) text,
    -- (tdsistolik) text,
    tfu text,
    pelayanancatatdibukukia text,
    treatmenttext text,
    highrisklabourfetussize text,
    nomorhp text,
    keterangank1k4who text,
    highrisklabourfetusnumber text,
    tandavitaltdsistolik text,
    -- (rujukan) text,
    keterangank1k4 text,
    -- (existinglocation) text,
    subvillage text,
    jamkesmas text,
    tandavitaltddiastolik text,
    hasilpemeriksaanlila text,
    -- (refdate) text,
    ancdate text,
    kepalajaninterhadappap text,
    komplikasilain text,
    -- (provinsi) text,
    komplikasidalamkehamilan text,
    treatment text,
    keadaanibusaattiba text,
    -- (submissiondate) text



    hipertensi_dalam_kehamilan boolean,
    abortus boolean,
    mola boolean,
    kehamilan_ektopit_terganggu boolean,
    hemoragi_post_partum boolean,
    ante_partum_beleding boolean,
    injeksi_jalan_lahir boolean,
    partum_kasep boolean,
    partus_lama boolean,
    demam_berdarah boolean,
    tifus_abdominalis boolean,
    sepsis boolean,
    pulmonal boolean,
    air_ketuban boolean,
    lain_lain boolean,
    tidak_ada_komplikasi boolean
);

