
CREATE TABLE sid_v2.tambah_anc (
    first_name character varying(75),
    last_name character varying(75),
    birth_date character varying(75),
    event_id character varying(75) UNIQUE,
    document_id character varying(75),
    base_entity_id character varying(75),
    location_id character varying(75),
    date_created timestamp without time zone,
    event_date timestamp without time zone,
    clientversionsubmissiondate timestamp with time zone,
    serverversionsubmissiondate timestamp with time zone,
    provider_id character varying(75),
    bbkg text,
    ---highriskstibbvs text,
    otherriskcongenitalabnormality text,
    lokasiperiksa text,
    ---village text,
    ---kabupaten text,
    riwayatkomplikasikebidananl text,
    trimesterke text,
    highriskheartdisorder text,
    province text,
    ---subvillage text,
    ---desa text,
    ---rpklainnya text,
    highriskpregnancyabortus text,
    ---provinsi text,
    persalinansebelumnya text,
    highriskpregnancyproteinenergymalnutrition text,
    ---malariarisk text,
    pptest text,
    tanggalhpht text,
    highriskasthma text,
    ---today text,
    tanggallahiranaksebelumnya text,
    penyakitkronisl text,
    highriskcardiovasculardiseaserecord text,
    ---tanggalperiksa text,
    highriskectopicpregnancy text,
    otherriskmolahidatidosa text,
    ---submissiondate text,
    highrisktuberculosis text,
    ---existinglocation text,
    alergi text,
    htp text,
    highrisklabourtbrisk text,
    ---highrisklaboursectioncesarearecordrisk text,
    address1 text,
    ---dusun text,
    partus text,
    hidup text,
    ---registrationdate text,
    ancid text,
    referencedate text,
    hasilpemeriksaanlila text,
    otherriskearlywaterbreak text,
    lokasiperiksaother text,
    cityvillage text,
    penyakitkronis text,
    highriskdidneydisorder text,
    highriskmalaria text,
    gravida text,
    riwayatkomplikasikebidanan text,
    ---lilacm text,
    ---regdate text,
    ---hpht text,
    usiaklinis text,
    type text,
    ---highriskkidneydisorder text,
    highriskhivaids text,
    district text,
    abortus text,
    ---rkklainnya text,
    tbcm text,
    highriskpregnancytoomanychildren text,
    subdistrict text,
    tanggalmemperolehbukukia text,
    jamkesmas text,
    ---kecamatan text,
    highrisklaboursectioncesarearecord text,

    hipertensi boolean,
    diabetes_melitus boolean,
    kelainan_jantung boolean,
    kelainan_ginjal boolean,
    kelainan_hati boolean,
    malaria boolean,
    asma boolean,
    sifilis boolean,
    HBV boolean,
    hiv_aids boolean,
    tbc boolean,
    penyakit_kronis_lainnya boolean
);

