CREATE TABLE IF NOT EXISTS sid3.blood_test (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		tandavitaltddiastolik text,
pulse text,
tandavitaltdsistolik text,
tddiastolik text,
tdsistolik text,
today text,
submissiondate text,
village text,
district text,
province text,
subdistrict text,
ahr text,
existinglocation text,
subvillage text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.edit_anc (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		tanggalperiksa text,
rkklainnya text,
rpklainnya text,
tanggalhpht text,
tanggalmemperolehbukukia text,
tbcm text,
partus text,
jamkesmas text,
today text,
registrationdate text,
referencedate text,
hpht text,
bbkg text,
hidup text,
persalinansebelumnya text,
htp text,
gravida text,
penyakitkronisl text,
hasilpemeriksaanlila text,
regdate text,
riwayatkomplikasikebidanan text,
riwayatkomplikasikebidananl text,
penyakitkronis text,
alergi text,
submissiondate text,
abortus text,
trimesterke text,
lilacm text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.tambah_anc (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		bbkg text,
highriskstibbvs text,
otherriskcongenitalabnormality text,
lokasiperiksa text,
village text,
kabupaten text,
riwayatkomplikasikebidananl text,
trimesterke text,
highriskheartdisorder text,
province text,
subvillage text,
desa text,
rpklainnya text,
highriskpregnancyabortus text,
provinsi text,
persalinansebelumnya text,
highriskpregnancyproteinenergymalnutrition text,
malariarisk text,
pptest text,
tanggalhpht text,
highriskasthma text,
today text,
tanggallahiranaksebelumnya text,
penyakitkronisl text,
highriskcardiovasculardiseaserecord text,
tanggalperiksa text,
highriskectopicpregnancy text,
otherriskmolahidatidosa text,
submissiondate text,
highrisktuberculosis text,
existinglocation text,
alergi text,
htp text,
highrisklabourtbrisk text,
highrisklaboursectioncesarearecordrisk text,
address1 text,
dusun text,
partus text,
hidup text,
registrationdate text,
ancid text,
referencedate text,
hasilpemeriksaanlila text,
otherriskearlywaterbreak text,
lokasiperiksaother text,
cityvillage text,
penyakitkronis text,
highriskdidneydisorder text,
highriskmalaria text,
gravida text,
riwayatkomplikasikebidanan text,
lilacm text,
regdate text,
hpht text,
usiaklinis text,
type text,
highriskkidneydisorder text,
highriskhivaids text,
district text,
abortus text,
rkklainnya text,
tbcm text,
highriskpregnancytoomanychildren text,
subdistrict text,
tanggalmemperolehbukukia text,
jamkesmas text,
kecamatan text,
highrisklaboursectioncesarearecord text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.rencana_persalinan (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		subvillage text,
address1 text,
htp text,
lokasiperiksa text,
rencanapendampingpersalinan text,
submissiondate text,
village text,
tanggal text,
pendonor text,
today text,
ancid text,
tanggalkunjunganrencanapersalinan text,
rencanapenolongpersalinan text,
tempatrencanapersalinan text,
cityvillage text,
lokasiperiksaother text,
transportasi text,
kondisirumah text,
persediaanperlengkapanpersalinan text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.edit_ibu (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		lokasiperiksaother text,
province text,
noibu text,
agama text,
golongandarah text,
registrationdate text,
existinglocation text,
kabupaten text,
desa text,
puskesmas text,
today text,
regdate text,
gps text,
subdistrict text,
district text,
subvillage text,
highriskpregnancyoldmaternalage text,
pasienwilayah text,
uniqueid text,
tanggallahir text,
asuransijiwa text,
nomortelponhp text,
village text,
dusun text,
umur text,
namadukun text,
pekerjaan text,
nik text,
namalengkap text,
namasuami text,
pendidikan text,
tanggalregistrasi text,
tglpindah text,
provinsi text,
tanggallahiribu text,
alamatdomisili text,
gakintidak text,
posyandu text,
namakader text,
tanggalperiksa text,
lokasiperiksa text,
pasienpindahan text,
kecamatan text,
highriskpregnancyyoungmaternalage text,
jeniskontrasepsi text,
submissiondate text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.kunjungan_pnc (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		rujukan text,
village text,
lokasiperiksa text,
integrasiprogramantitb text,
komplikasi text,
keadaantiba text,
highriskpostpartumhemorrhage text,
regdate text,
harikekf text,
treatmenttext text,
address1 text,
lokasiperiksaother text,
tanggalkunjungan text,
pncdate text,
nik text,
dirujukkelainnya text,
komplikasilainnya text,
highriskpostpartumdistosia text,
today text,
submissiondate text,
existinglocation text,
tandavitaltddiastolik text,
tandavitalsuhu text,
integrasiprogramfotothorax text,
registrationdate text,
keterangan text,
keadaanpulang text,
highriskpostpartumpih text,
highriskpostpartummaternalsepsis text,
ancid text,
vitamina24jampp text,
daruratnifas text,
dirujukke text,
kondisipascatindakan text,
treatment text,
highriskpostpartuminfection text,
highriskpostpartummastitis text,
cityvillage text,
tanggallahiranak text,
integrasiprogramantimalaria text,
penanganannifas text,
subvillage text,
tandavitaltdsistolik text,
pelayananfe text,
vitamina2jampp text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.tambah_bayi (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		lokasiperiksaother text,
deviceid text,
simserial text,
phonenumber text,
address1 text,
tanggalperiksa text,
subdistrict text,
subvillage text,
kabupaten text,
kecamatan text,
tanggalpendaftaran text,
province text,
district text,
generatednotename14 text,
provinsi text,
desa text,
dusun text,
lokasiperiksa text,
today text,
village text,
cityvillage text,
generatednotename13 text,
existinglocation text,
instanceid text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.edit_tambah_kb (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		tanggallahiribu text,
umur text,
dusun text,
lokasiperiksaother text,
today text,
submissiondate text,
subdistrict text,
tanggalperiksa text,
kecamatan text,
tddiastolik text,
alkihb text,
alkilila text,
keterangantentangpesertakb text,
regdate text,
existinglocation text,
provinsi text,
tanggallahir text,
alkipenyakitkronis text,
cityvillage text,
tanggalkunjungan text,
lokasiperiksa text,
namalengkap text,
kabupaten text,
desa text,
paritas text,
alkipenyakitims text,
jeniskontrasepsi text,
registrationdate text,
subvillage text,
address1 text,
district text,
tdsistolik text,
village text,
province text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.register_anc (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		ishighriskreason text,
highriskpregnancyreason text,
partus text,
riwayatkomplikasikebidanan text,
penyakitkronis text,
jamkesmas text,
integrasiprogrampmtctserologi text,
komplikasidalamkehamilan text,
tanggallahiribu text,
nomortelponhp text,
integrasiprogrampmtctperiksadarah text,
keadaanibusaattiba text,
diabetesrisk text,
gakintidak text,
djj text,
proteinenergymalnutritionrisk text,
fetusmalpresentationrisk text,
malariarisk text,
taksiranberatjanin text,
pelayanancatatdibukukia text,
keterangan text,
heartdisorderrisk text,
caramasuktempatpelayanan text,
earlywaterbreakrisk text,
highrisklabourreason text,
pelayananinjeksitt text,
laboratoriumthalasemia text,
integrasiprogrammalariamalaria text,
fetussizerisk text,
zectioncesarearecordrisk text,
ishighrisklabour text,
tbcm text,
integrasiprogrampmtctarvprofilaksis text,
keadaanibusaatpulang text,
fetusnumberrisk text,
sectioncesarearecordrisk text,
alergi text,
bukukia text,
cardiovasculardiseaserecordrisk text,
tanggalperiksa text,
bbsebelumhamil text,
ishighrisk text,
kabupaten text,
kepalajaninterhadappap text,
tbrisk text,
ectopicpregnancyrisk text,
hivaidsrisk text,
puskesmas text,
pihrisk text,
tbcrisk text,
toomanychildrenrisk text,
congenitalabnormalityrisk text,
isotherrisk text,
posyandu text,
namakader text,
tfu text,
integrasiprogrampmtctarv text,
dirujukke text,
molahidatidosarisk text,
agama text,
tanggalmemperolehbukukia text,
tddiastolik text,
tanggallahir text,
htp text,
today text,
laboratoriumperiksahbdilakukan text,
integrasiprogramtbtbc text,
abortusrisk text,
highrisknote text,
golongandarah text,
hasilpemeriksaanlila text,
pelayanancatatbukukia text,
integrasiprogrammalariakelambuberinsektisida text,
namadukun text,
integrasiprogramtbdahak text,
integrasiprogramtbobat text,
regdate text,
bbkg2 text,
programintegration text,
resikoterdeteksipertamakalioleh text,
kecamatan text,
rkk text,
rkklainnya text,
laboratoriumguladarah text,
noibu text,
tdsistolik text,
stibbvsrisk text,
kidneydisorderrisk text,
asthmarisk text,
referencedate text,
telponmemilikitidak text,
gravida text,
ancke text,
tandavitaltdsistolik text,
tooyoungrisk text,
alamatdomisili text,
desa text,
rpklainnya text,
integrasiprogrammalariaperiksadarah text,
integrasiprogrammalariakelambu text,
kecamatanl text,
bbkg text,
dirujukkel text,
otherriskreason text,
submissiondate text,
pekerjaan text,
hidup text,
persentasijanin text,
laboratoriumhbsag text,
anemiarisk text,
tuberculosisrisk text,
persalinansebelumnya text,
statusgiziibu text,
integrasiprogrammalariaobat text,
rujukan text,
kepalaterhadapjaninpap text,
laboratoriumsifilis text,
umur text,
asuransijiwa text,
nomortelpon text,
kelainanbentuk text,
trimesterke text,
tandavitaltddiastolik text,
registrationdate text,
namalengkap text,
pendidikan text,
jumlahjanin text,
resikoterdeksipertamakali text,
namasuami text,
abortus text,
kronis text,
statusimunisasitt text,
pelayananfe text,
ishighriskpregnancy text,
lainlain text,
bbkg1 text,
lilacm text,
reflekspatelaibu text,
laboratoriumperiksahbhasil text,
laboratoriumperiksahbanemia text,
laboratoriumproteinuria text,
propinsi text,
dusun text,
tanggalhpht text,
anamnesisibu text,
labcheck text,
integrasiprogrampmtctvct text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.pnc_edit (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		komplikasi text,
komplikasilainlain text,
alamatbersalin text,
keadaanbayi text,
perdarahankalaiv2jampostpartum text,
dirujukkelainlain text,
submissiondate text,
keadaanibu text,
tanggalkalaiaktif text,
pelayanan text,
persalinan text,
jamplasentalahir text,
tanggalkalaii text,
carapersalinanibu text,
registrationdate text,
usiakehamilan text,
jamkalaiaktif text,
tanggalplasentalahir text,
persentasi text,
integrasiprogram text,
dirujukke text,
kepemilikanbukukia text,
hpht text,
jamkalaii text,
regdate text,
penolonglainlain text,
today text,
penolonglainlainln text,
manajemenaktifkalaiii text,
tempatbersalin text,
penolong text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.kunjungan_anc_lab_test (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		laboratoriumguladarah text,
treatmentthalasemiatxt text,
regdate text,
lokasiperiksa text,
treatmentanemiatxt text,
treatmentproturintxt text,
laboratoriumperiksahbanemia text,
laboratoriumproteinuria text,
cityvillage text,
subvillage text,
treatmentdiabetestxt text,
highriskpregnancyanemia text,
submissiondate text,
village text,
today text,
existinglocation text,
referencedate text,
laboratoriumthalasemia text,
treatmenthbsagtxt text,
lokasiperiksaother text,
laboratoriumperiksahbhasil text,
treatmentsifilistxt text,
laboratoriumhbsag text,
registrationdate text,
ancid text,
address1 text,
laboratoriumsifilis text,
highriskpregnancydiabetes text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.register_pnc_oa (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		desa text,
keadaanibu text,
highriskpostpartumhemorrhage text,
highriskpostpartuminfection text,
province text,
noibu text,
usiakehamilan text,
regdate text,
kecamatan text,
gakintidak text,
namakader text,
persalinan text,
pelayanan text,
namabayi text,
highriskpostpartumvacum text,
beratbayi text,
persentasi text,
tanggallahiranak text,
highriskpregnancyoldmaternalage text,
highriskpostpartumpreeclampsiaeclampsia text,
highriskpostpartumforceps text,
pekerjaan text,
posyandu text,
tanggalkalaiaktif text,
tempat text,
manajemenaktifkalaiii text,
nik text,
subvillage text,
puskesmas text,
alamatdomisili text,
nomortelponhp text,
tanggalplasentalahir text,
jamplasentalahir text,
jeniskelamin text,
dusun text,
namasuami text,
pptest text,
highriskpostpartummaternalsepsis text,
uniqueid text,
subdistrict text,
tanggalkalaii text,
carapersalinanibu text,
integrasiprogram text,
komplikasilainlain text,
dirujukkelainlain text,
highriskpregnancyyoungmaternalage text,
highriskchildlowbirthweght text,
umur text,
keadaanbayi text,
jamkalaiaktif text,
tempatbersalin text,
penolonglainlain text,
highriskpostpartumdistosia text,
highriskpostpartumpih text,
highriskpostpartumsectiocaesaria text,
provinsi text,
beratlahir text,
nobayi text,
golongandarah text,
perdarahankalaiv2jampostpartum text,
today text,
submissiondate text,
registrationdate text,
district text,
namalengkap text,
pendidikan text,
lokasiperiksa text,
village text,
kabupaten text,
tanggallahiribu text,
tanggallahir text,
agama text,
namadukun text,
asuransijiwa text,
hpht text,
penolong text,
komplikasi text,
dirujukke text,
alamatbersalin text,
jamkalaii text,
highriskchildpreterm text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.kunjungan_balita (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		kunjunganbayike text,
panjangbayi text,
tanggalpemeriksaananakbalita text,
hasilpengukurantinggianakbalita text,
indikatorberatbadanbayi text,
asiaksklusif text,
statusgizi text,
pelayananvita text,
statussesehatanbayi text,
tanggalkunjunganbayiperbulan text,
kpsppenyimpangan text,
desaanak text,
penyakit text,
babyage text,
hasildilakukannyakpsp text,
today text,
village text,
existinglocation text,
lokasiperiksaother text,
hasilpenimbangananakbalita text,
pemberianasieksklusif text,
statuskesehatanbayi text,
mtbs text,
dirujukkebayi text,
dirujukkelainnyabayi text,
lokasiperiksa text,
beratbayi text,
rujukanbayi text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.edit_bayi (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		ibuentityid text,
ibucaseid text,
tanggallahir text,
jeniskelamin text,
today text,
beratbadansaatlahir text,
existinglocation text,
submissiondate text,
nobayi text,
tanggallahiranak text,
desaanak text,
beratlahir text,
referencedate text,
namabayi text,
kepemilikanbukukia text,
childexistinglocation text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.kohort_pelayanan_kb (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		subvillage text,
jeniskontrasepsiyangdigunakan text,
cityvillage text,
keterangantentangpesertakb text,
keteranganefeksamping text,
today text,
village text,
tanggalkunjungan text,
keteranganganticara text,
keterangankomplikasi text,
submissiondate text,
registrationdate text,
address1 text,
lokasiperiksa text,
jeniskontrasepsi text,
keterangantentangpesertakb2 text,
regdate text,
existinglocation text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.kunjungan_anc (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		keadaanibusaatpulang text,
province text,
ancke text,
lilacm text,
jumlahjanin text,
pelayanancatatbukukia text,
dusun text,
tddiastolik text,
reflekspatelaibu text,
taksiranberatjanin text,
referencedate text,
pelayananfe text,
lainlain text,
dirujuk text,
kabupaten text,
lokasiperiksa text,
nomortelponhp text,
trimesterke text,
djj text,
ancid text,
highriskpregnancypih text,
keterangan text,
highrisklabourfetusmalpresentation text,
district text,
address1 text,
nomortelpon text,
caramasuktempatpelayanan text,
bbkg text,
persentasijanin text,
highriskpregnancyproteinenergymalnutrition text,
today text,
hiddenancke text,
cityvillage text,
tanggalhpht text,
statusgiziibu text,
jumlahfe text,
dirujukkel text,
dirujukke text,
registrationdate text,
village text,
usiaklinis text,
anamnesisibu text,
kepalaterhadapjaninpap text,
pelayananinjeksitt text,
kunjunganke text,
statusimunisasitt text,
regdate text,
subdistrict text,
kecamatan text,
desa text,
lokasiperiksaother text,
hpht text,
tdsistolik text,
tfu text,
pelayanancatatdibukukia text,
treatmenttext text,
highrisklabourfetussize text,
nomorhp text,
keterangank1k4who text,
highrisklabourfetusnumber text,
tandavitaltdsistolik text,
rujukan text,
keterangank1k4 text,
existinglocation text,
subvillage text,
jamkesmas text,
tandavitaltddiastolik text,
hasilpemeriksaanlila text,
refdate text,
ancdate text,
kepalajaninterhadappap text,
komplikasilain text,
provinsi text,
komplikasidalamkehamilan text,
treatment text,
keadaanibusaattiba text,
submissiondate text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.penutupan_ibu (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		cityvillage text,
address1 text,
otherclosereason text,
confirmecclose text,
iskicloseconfirmed text,
notmaternaldeathcause text,
maternaldeathcause text,
referred text,
today text,
registrationdate text,
birthattendant text,
prereferralmanagement text,
village text,
existinglocation text,
closereasonother text,
maternaldeathdate text,
otherplaceofdeath text,
othermaternaldeathcause text,
submissiondate text,
subvillage text,
closereason text,
placeofdeath text,
referrallocation text,
regdate text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.identitas_ibu (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		provinsi text,
pekerjaan text,
posyandu text,
namadukun text,
highriskpregnancyoldmaternalage text,
tanggalregistrasi text,
lokasiperiksa text,
district text,
dusun text,
tanggallahiribu text,
tanggallahir text,
asuransijiwa text,
nomortelponhp text,
jeniskontrasepsi text,
province text,
namalengkap text,
pendidikan text,
submissiondate text,
kabupaten text,
gakintidak text,
golongandarah text,
today text,
regdate text,
subdistrict text,
desa text,
noibu text,
existinglocation text,
tanggalperiksa text,
lokasiperiksaother text,
pasienwilayah text,
pasienpindahan text,
tglpindah text,
nik text,
umur text,
alamatdomisili text,
agama text,
namakader text,
registrationdate text,
gps text,
uniqueid text,
village text,
namasuami text,
highriskpregnancyyoungmaternalage text,
subvillage text,
kecamatan text,
puskesmas text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.penutupan_kb (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		keterangando text,
submissiondate text,
address1 text,
confirmkbclose text,
today text,
regdate text,
subvillage text,
kbclosereason text,
keterangangagal text,
registrationdate text,
jeniskontrasepsi text,
village text,
cityvillage text,
deathdate text,
iskbcloseconfirmed text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.penutupan_pnc (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		cityvillage text,
deathdate text,
othermaternaldeathcause text,
ispnccloseconfirmed text,
submissiondate text,
regdate text,
registrationdate text,
village text,
pncclosereason text,
placeofdeath text,
otherplaceofdeath text,
address1 text,
notmaternaldeathcause text,
ancid text,
existinglocation text,
maternaldeathcause text,
confirmpncclose text,
today text,
subvillage text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.post_partum_kb (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		ancid text,
address1 text,
pelaksanaank42hari text,
pelaksanaanl42hari text,
today text,
registrationdate text,
metodekontrasepsi text,
pelaksanaanatas42hari text,
regdate text,
existinglocation text,
village text,
cityvillage text,
subvillage text,
rencana text,
pelaksanaanbawah42hari text,
submissiondate text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.penutupan_anak (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		closereason text,
childdeathcause text,
referred text,
referrallocation text,
submissiondate text,
confirmchildclose text,
village text,
existingsubvillage text,
placeofdeath text,
prereferralmanagement text,
existinglocation text,
desaanak text,
subvillage text,
childdeathcauseother text,
today text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.imunisasi_bayi (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		ipv text,
campak text,
campaklanjutan text,
lokasiperiksa text,
dpthb2 text,
polio4 text,
bcg text,
polio2 text,
dpthb3 text,
village text,
subvillage text,
hb0 text,
desaanak text,
today text,
polio3 text,
dpthblanjutan text,
childexistinglocation text,
polio1 text,
dpthb1 text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.register_bayi_oa (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		provinsi text,
noibu text,
submissiondate text,
dusun text,
nobayi text,
beratlahir text,
registrationdate text,
village text,
highriskpregnancyoldmaternalage text,
province text,
subdistrict text,
kabupaten text,
namabayi text,
highriskpregnancyyoungmaternalage text,
today text,
uniqueid text,
subvillage text,
kecamatan text,
tanggallahiranak text,
district text,
desa text,
namalengkap text,
alamatdomisili text,
highrisklowbirthweight text,
namasuami text,
jeniskelamin text,
highriskchildlowbirthweght text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.penutupan_anc (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		otherclosereason text,
maternaldeathcause text,
notematernaldeathcause text,
isanccloseconfirmed text,
today text,
prereferralmanagement text,
cityvillage text,
subvillage text,
closereason text,
datematernaldeath text,
maternaldeathdate text,
placeofdeath text,
birthattendant text,
referrallocation text,
confirmancclose text,
hasancleftplace text,
desa text,
dusun text,
othermaternaldeathcause text,
otherplaceofdeath text,
confirmancleft text,
submissiondate text,
village text,
existinglocation text,
address text,
referred text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.balita_kunjungan (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		b05012 text,
hasildilakukannyakpsp text,
pemberianvitadankondisibalitasaatsakit text,
today text,
submissiondate text,
tanggalkunjunganbayiperbulan text,
b05010 text,
b05011 text,
beratbadanbayisetiapkunjunganbayiperbulan text,
b01004 text,
regdate text,
registrationdate text,
lokasiperiksa text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.kunjungan_neonatal (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		tanggallahir text,
komplikasineonatallain text,
highriskchildasphyxia text,
suhubayi text,
hb0 text,
komplikasineonatal text,
highriskchildtetanusneonatorum text,
tanggalkunjunganbayiperbulan text,
panjangbayi text,
highriskchildbirthtrauma text,
regdate text,
village text,
desaanak text,
tanggallahiranak text,
neonatal text,
frekuensinapas text,
kondisibayi text,
confirmofdeath text,
subvillage text,
komplikasineonataltertangani text,
highriskchilditerus text,
today text,
beratbayi text,
dirujukkeneonatal text,
dirujukkelainnyaneonatal text,
registrationdate text,
existinglocation text,
kunjunganneonatal text,
tanggalkunjunganneonatal text,
jenispelayanan text,
highriskchildneonatalsepsis text,
submissiondate text,
frekuensidenyutjantung text,
pemberianimunisasihb text,
rujukanneonatal text,
highriskchildcongenitalabnormality text,
highriskchildhypothermia text,
highriskchildinfection text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.coaching_feedback_form (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		masalahpenggunaanlangsungsaatkunjungan text,
masalahlainnyaaplikasierror text,
datayangditampilkantidaksesuaidenganyangdimasukkankartuibu text,
tidakdapatmengeditdatakohortkb text,
koneksiinternetdiposyandulemah text,
pengisidayarusaktidakberfungsi text,
masalahlainnyabaterai text,
waktumenyimpanformlama text,
tidakdapatmengeditdatakohortanak text,
masalahlainnyaregisterpnc text,
koneksiinternetdipolindespuskesmaslemah text,
aplikasimenutupsendiri text,
pilihanvariabelyangadatidaksesuaikartuibu text,
tidakdapatmemasukkandatatertentukohortkb text,
masalahregisteranc text,
tidakdapatmemasukkandatatertenturegisteranc text,
rentangdatavariabeltidaksesuairegisterpnc text,
kalkulasivariabeltidaksesuaikohortanak text,
responlayarsentuhlama text,
masalahaplikasierror text,
datavariabelyangdimasukkanhilangkartuibu text,
pilihanvariabelyangadatidaksesuaikohortkb text,
rentangdatavariabeltidaksesuaikohortanak text,
tidakdapatmemasukkandatatertentukohortanak text,
tidakdapatmengeditdataregisterpnc text,
masalahlainnyakohortanak text,
submissiondate text,
bidanid text,
kuotainternettelahhabis text,
kalkulasivariabeltidaksesuaikohortkb text,
datayangditampilkantidaksesuaidenganyangdimasukkanregisteranc text,
baterai text,
formentrikohortkb text,
tidakdapatmemasukkandatatertenturegisterpnc text,
datavariabelyangdimasukkanhilangkohortanak text,
coachingdate text,
bateraicepathabis text,
aplikasierror text,
tidakdapatmengeditdatakartuibu text,
datavariabelyangdimasukkanhilangkohortkb text,
datavariabelyangdimasukkanhilangregisteranc text,
username text,
masalah text,
masalahkoneksiinternet text,
tablettibatibamati text,
today text,
formentriregisteranc text,
masalahkohortanak text,
pilihanvariabelyangadatidaksesuaikohortanak text,
masalahsinkronisasidata text,
masalahlainnyakartuibu text,
rentangdatavariabeltidaksesuaikohortkb text,
masalahlainnyakohortkb text,
formentriregisterpnc text,
masalahregisterpnc text,
datayangditampilkantidaksesuaidenganyangdimasukkankohortanak text,
pengunaanaplikasi text,
waktuloadingformlama text,
masalahkartuibu text,
kalkulasivariabeltidaksesuaikartuibu text,
pilihanvariabelyangadatidaksesuairegisteranc text,
formentrikohortanak text,
tidakdapatlogin text,
masalahlainnyapenggunaanlangsung text,
rentangdatavariabeltidaksesuaikartuibu text,
masalahkohortkb text,
pilihanvariabelyangadatidaksesuairegisterpnc text,
umpanbaliklainnya text,
keteranganumpanbaliklainnya text,
masalahbaterai text,
pengisianbaterailama text,
tidakdapatmemasukkandatatertentukartuibu text,
rentangdatavariabeltidaksesuairegisteranc text,
datayangditampilkantidaksesuaidenganyangdimasukkanregisterpnc text,
masalahlainnyapenggunaanaplikasi text,
formentrikartuibu text,
datayangditampilkantidaksesuaidenganyangdimasukkankohortkb text,
kalkulasivariabeltidaksesuairegisteranc text,
respondentname text,
tidakdapatmengeditdataregisteranc text,
koneksiinternet text,
datavariabelyangdimasukkanhilangregisterpnc text,
kalkulasivariabeltidaksesuairegisterpnc text,
masalahlainnyakoneksiinternet text,
masalahpenggunaanaplikasi text,
penggunaanlangsungsaatkunjungan text,
masalahlainnyaregisteranc text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.kunjungan_anc_integrasi (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		village text,
cityvillage text,
subvillage text,
address1 text,
lokasiperiksaother text,
referencedate text,
integrasiprogrampmtctperiksadarah text,
integrasiprogrammalariaperiksadarah text,
integrasiprogrammalariaobat text,
integrasiprogrammalariakelambuberinsektisida text,
integrasiprogramtbobat text,
today text,
submissiondate text,
existinglocation text,
lokasiperiksa text,
integrasiprogrampmtctvct text,
integrasiprogrampmtctarvprofilaksis text,
integrasiprogrammalariakelambu text,
integrasiprogramtbdahak text,
highriskmalaria text,
ancid text,
integrasiprogrampmtctarv text,
integrasiprogrampmtctserologi text,
highrisktbc text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.kohort_kunjungan_bayi_perbulan (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		indikatorberatbadanbayi text,
penyakit text,
rujukanbayi text,
lokasiperiksa text,
lokasiperiksaother text,
subvillage text,
mtbs text,
dirujukkebayi text,
pelayananvita text,
statusgizi text,
village text,
tanggalkunjunganbayiperbulan text,
beratbayi text,
pemberianasieksklusif text,
hasildilakukannyakpsp text,
existinglocation text,
indikatorberatbedanbayi text,
dirujukkelainnyabayi text,
submissiondate text,
kunjunganbayike text,
panjangbayi text,
beratbadanbayisetiapkunjunganbayiperbulan text,
today text,
babyage text,
statuskesehatanbayi text,
desaanak text,
asiaksklusif text,
kpsppenyimpangan text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.update_photo (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		cityvillage text,
subvillage text,
address1 text,
existinglocation text,
today text,
submissiondate text,
facevector text,
village text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.dokumentasi_persalinan (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		persalinan text,
tanggalkalaii text,
carapersalinanibu text,
integrasiprogram text,
treatment text,
submissiondate text,
cityvillage text,
keadaanibu text,
manajemenaktifkalaiii text,
komplikasi text,
alamatbersalin text,
highriskpostpartumdistosia text,
lokasiperiksa text,
tanggalplasentalahir text,
persentasi text,
highriskpostpartuminfection text,
highriskpostpartummaternalsepsis text,
address1 text,
perdarahankalaiv2jampostpartum text,
jamkalaiaktif text,
jamkalaii text,
tempat text,
komplikasilainlain text,
dirujukke text,
dirujukkelainlain text,
keadaanbayi text,
tanggalkalaiaktif text,
highriskpostpartumeclampsia text,
highriskpostpartumsectiocaesaria text,
treatmenttext text,
tempatbersalin text,
highriskpostpartumpreeclampsiaeclampsia text,
usiakehamilan text,
penolonglainlain text,
highriskpostpartumpih text,
highriskpostpartumhemorrhage text,
today text,
referencedate text,
subvillage text,
hpht text,
tanggalhpht text,
highriskpostpartumvacum text,
kepemilikanbukukia text,
ancid text,
existinglocation text,
penolong text,
pelayanan text,
highriskpostpartumpreeclampsia text,
highriskpostpartumforceps text,
village text,
jamplasentalahir text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.tambah_kb (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		address1 text,
dusun text,
tanggallahir text,
umur text,
paritas text,
jeniskontrasepsi text,
tanggalkunjungan text,
tddiastolik text,
alkipenyakitkronis text,
keterangantentangpesertakb text,
village text,
district text,
alkilila text,
submissiondate text,
existinglocation text,
cityvillage text,
tanggallahiribu text,
regdate text,
namalengkap text,
desa text,
alkipenyakitims text,
registrationdate text,
lokasiperiksaother text,
tdsistolik text,
subdistrict text,
subvillage text,
provinsi text,
kabupaten text,
tanggalperiksa text,
lokasiperiksa text,
alkihb text,
province text,
kecamatan text,
today text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.tambah_kb_oa (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		pendidikan text,
agama text,
paritas text,
keterangantentangpesertakb text,
tanggalkunjungan text,
kabupaten text,
tanggallahiribu text,
subdistrict text,
provinsi text,
gakintidak text,
namakader text,
highrisknote text,
village text,
province text,
pekerjaan text,
subvillage text,
alamatdomisili text,
puskesmas text,
namasuami text,
posyandu text,
nomortelponhp text,
tddiastolik text,
nik text,
kecamatan text,
dusun text,
ishighrisk text,
regdate text,
alkihb text,
jeniskontrasepsi text,
toooldmother text,
umur text,
golongandarah text,
alkipenyakitkronis text,
tooyoungrisk text,
today text,
uniqueid text,
lokasiperiksa text,
tanggallahir text,
registrationdate text,
tdsistolik text,
district text,
noibu text,
namalengkap text,
pptest text,
alkilila text,
alkipenyakitims text,
jeniskontrasepsiyangdigunakan text,
submissiondate text,
desa text,
namadukun text,
asuransijiwa text);
---------------------------------------
