CREATE TABLE IF NOT EXISTS sid3.blood_test (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		subvillage text,
tdsistolik text,
tddiastolik text,
pulse text,
submissiondate text,
village text,
subdistrict text,
today text,
existinglocation text,
tandavitaltdsistolik text,
province text,
tandavitaltddiastolik text,
ahr text,
district text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.coaching_feedback_form (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		tablettibatibamati text,
masalahlainnyapenggunaanaplikasi text,
rentangdatavariabeltidaksesuaikohortkb text,
masalahregisterpnc text,
pilihanvariabelyangadatidaksesuaikohortanak text,
rentangdatavariabeltidaksesuaikohortanak text,
today text,
kalkulasivariabeltidaksesuaikartuibu text,
rentangdatavariabeltidaksesuaikartuibu text,
tidakdapatmemasukkandatatertentukartuibu text,
datayangditampilkantidaksesuaidenganyangdimasukkankohortkb text,
rentangdatavariabeltidaksesuairegisteranc text,
username text,
responlayarsentuhlama text,
penggunaanlangsungsaatkunjungan text,
masalahregisteranc text,
tidakdapatmengeditdataregisteranc text,
pilihanvariabelyangadatidaksesuairegisterpnc text,
tidakdapatmengeditdatakartuibu text,
rentangdatavariabeltidaksesuairegisterpnc text,
datavariabelyangdimasukkanhilangkohortanak text,
masalahbaterai text,
datavariabelyangdimasukkanhilangkohortkb text,
datavariabelyangdimasukkanhilangregisteranc text,
masalahlainnyakohortanak text,
respondentname text,
koneksiinternetdipolindespuskesmaslemah text,
kuotainternettelahhabis text,
tidakdapatlogin text,
baterai text,
formentriregisteranc text,
pilihanvariabelyangadatidaksesuairegisteranc text,
pengisianbaterailama text,
masalahpenggunaanlangsungsaatkunjungan text,
masalahaplikasierror text,
masalahsinkronisasidata text,
pilihanvariabelyangadatidaksesuaikohortkb text,
masalahlainnyaregisteranc text,
formentriregisterpnc text,
masalahkartuibu text,
tidakdapatmemasukkandatatertentukohortanak text,
umpanbaliklainnya text,
pilihanvariabelyangadatidaksesuaikartuibu text,
formentrikohortkb text,
tidakdapatmengeditdatakohortkb text,
datayangditampilkantidaksesuaidenganyangdimasukkanregisteranc text,
kalkulasivariabeltidaksesuaikohortanak text,
masalah text,
masalahlainnyaaplikasierror text,
datavariabelyangdimasukkanhilangkartuibu text,
masalahlainnyakohortkb text,
kalkulasivariabeltidaksesuairegisterpnc text,
tidakdapatmemasukkandatatertenturegisterpnc text,
koneksiinternet text,
masalahlainnyakoneksiinternet text,
masalahlainnyakartuibu text,
tidakdapatmemasukkandatatertentukohortkb text,
datavariabelyangdimasukkanhilangregisterpnc text,
tidakdapatmengeditdataregisterpnc text,
formentrikohortanak text,
bidanid text,
masalahkoneksiinternet text,
datayangditampilkantidaksesuaidenganyangdimasukkankartuibu text,
masalahkohortkb text,
tidakdapatmemasukkandatatertenturegisteranc text,
masalahkohortanak text,
coachingdate text,
koneksiinternetdiposyandulemah text,
masalahlainnyabaterai text,
masalahpenggunaanaplikasi text,
masalahlainnyapenggunaanlangsung text,
aplikasimenutupsendiri text,
formentrikartuibu text,
datayangditampilkantidaksesuaidenganyangdimasukkankohortanak text,
tidakdapatmengeditdatakohortanak text,
submissiondate text,
pengunaanaplikasi text,
waktuloadingformlama text,
datayangditampilkantidaksesuaidenganyangdimasukkanregisterpnc text,
keteranganumpanbaliklainnya text,
bateraicepathabis text,
pengisidayarusaktidakberfungsi text,
kalkulasivariabeltidaksesuaikohortkb text,
kalkulasivariabeltidaksesuairegisteranc text,
waktumenyimpanformlama text,
aplikasierror text,
masalahlainnyaregisterpnc text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.penutupan_anc (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		othermaternaldeathcause text,
otherplaceofdeath text,
birthattendant text,
village text,
cityvillage text,
subvillage text,
datematernaldeath text,
maternaldeathcause text,
dusun text,
placeofdeath text,
address text,
referred text,
confirmancclose text,
existinglocation text,
desa text,
prereferralmanagement text,
confirmancleft text,
isanccloseconfirmed text,
hasancleftplace text,
today text,
closereason text,
otherclosereason text,
maternaldeathdate text,
notematernaldeathcause text,
referrallocation text,
submissiondate text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.edit_anc (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		abortus text,
hidup text,
riwayatkomplikasikebidananl text,
partus text,
submissiondate text,
gravida text,
penyakitkronis text,
today text,
regdate text,
rpklainnya text,
tbcm text,
lilacm text,
jamkesmas text,
referencedate text,
hpht text,
trimesterke text,
riwayatkomplikasikebidanan text,
registrationdate text,
penyakitkronisl text,
alergi text,
tanggalhpht text,
htp text,
bbkg text,
tanggalperiksa text,
persalinansebelumnya text,
rkklainnya text,
hasilpemeriksaanlila text,
tanggalmemperolehbukukia text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.tambah_anc (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		submissiondate text,
registrationdate text,
tanggallahiranaksebelumnya text,
usiaklinis text,
tbcm text,
highriskpregnancytoomanychildren text,
otherriskearlywaterbreak text,
highriskasthma text,
kecamatan text,
persalinansebelumnya text,
hasilpemeriksaanlila text,
highriskpregnancyproteinenergymalnutrition text,
highriskcardiovasculardiseaserecord text,
lokasiperiksa text,
province text,
ancid text,
penyakitkronisl text,
tanggalmemperolehbukukia text,
bbkg text,
desa text,
highrisklaboursectioncesarearecord text,
subdistrict text,
subvillage text,
penyakitkronis text,
htp text,
otherriskcongenitalabnormality text,
kabupaten text,
highrisklaboursectioncesarearecordrisk text,
highriskectopicpregnancy text,
lokasiperiksaother text,
village text,
highriskstibbvs text,
otherriskmolahidatidosa text,
today text,
dusun text,
tanggalhpht text,
highrisklabourtbrisk text,
district text,
partus text,
hidup text,
jamkesmas text,
highriskkidneydisorder text,
highriskdidneydisorder text,
cityvillage text,
referencedate text,
abortus text,
alergi text,
riwayatkomplikasikebidananl text,
lilacm text,
highriskheartdisorder text,
type text,
highrisktuberculosis text,
provinsi text,
gravida text,
riwayatkomplikasikebidanan text,
rpklainnya text,
highriskmalaria text,
highriskhivaids text,
existinglocation text,
rkklainnya text,
malariarisk text,
highriskpregnancyabortus text,
tanggalperiksa text,
hpht text,
pptest text,
address1 text,
trimesterke text,
regdate text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.register_anc (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		tanggallahir text,
htp text,
anamnesisibu text,
tandavitaltdsistolik text,
persentasijanin text,
statusimunisasitt text,
tdsistolik text,
djj text,
integrasiprogrampmtctserologi text,
ectopicpregnancyrisk text,
alamatdomisili text,
kecamatan text,
trimesterke text,
kepalajaninterhadappap text,
pelayananinjeksitt text,
laboratoriumsifilis text,
otherriskreason text,
puskesmas text,
desa text,
reflekspatelaibu text,
taksiranberatjanin text,
lainlain text,
fetusmalpresentationrisk text,
agama text,
gravida text,
integrasiprogrammalariamalaria text,
komplikasidalamkehamilan text,
pihrisk text,
tooyoungrisk text,
ishighrisk text,
kabupaten text,
penyakitkronis text,
tanggalmemperolehbukukia text,
integrasiprogrampmtctarv text,
anemiarisk text,
zectioncesarearecordrisk text,
earlywaterbreakrisk text,
bukukia text,
resikoterdeksipertamakali text,
hivaidsrisk text,
asthmarisk text,
tuberculosisrisk text,
highriskpregnancyreason text,
proteinenergymalnutritionrisk text,
registrationdate text,
kepalaterhadapjaninpap text,
integrasiprogrampmtctarvprofilaksis text,
namakader text,
tanggalhpht text,
integrasiprogrampmtctvct text,
rkk text,
riwayatkomplikasikebidanan text,
tbcm text,
stibbvsrisk text,
noibu text,
pendidikan text,
pekerjaan text,
rpklainnya text,
tddiastolik text,
statusgiziibu text,
pelayanancatatdibukukia text,
malariarisk text,
dusun text,
keadaanibusaattiba text,
sectioncesarearecordrisk text,
heartdisorderrisk text,
ishighrisklabour text,
hidup text,
hasilpemeriksaanlila text,
integrasiprogrammalariakelambu text,
highrisknote text,
umur text,
asuransijiwa text,
ancke text,
tfu text,
jumlahjanin text,
tbrisk text,
congenitalabnormalityrisk text,
referencedate text,
namadukun text,
golongandarah text,
caramasuktempatpelayanan text,
integrasiprogrampmtctperiksadarah text,
integrasiprogrammalariaobat text,
keterangan text,
abortusrisk text,
molahidatidosarisk text,
namalengkap text,
bbkg1 text,
laboratoriumperiksahbhasil text,
diabetesrisk text,
persalinansebelumnya text,
tandavitaltddiastolik text,
programintegration text,
partus text,
bbsebelumhamil text,
laboratoriumguladarah text,
ishighriskreason text,
isotherrisk text,
today text,
namasuami text,
telponmemilikitidak text,
kronis text,
pelayanancatatbukukia text,
laboratoriumperiksahbdilakukan text,
integrasiprogramtbdahak text,
posyandu text,
kelainanbentuk text,
jamkesmas text,
pelayananfe text,
laboratoriumperiksahbanemia text,
integrasiprogrammalariaperiksadarah text,
integrasiprogrammalariakelambuberinsektisida text,
keadaanibusaatpulang text,
toomanychildrenrisk text,
kidneydisorderrisk text,
tanggalperiksa text,
dirujukkel text,
abortus text,
bbkg2 text,
lilacm text,
integrasiprogramtbobat text,
ishighriskpregnancy text,
rkklainnya text,
resikoterdeteksipertamakalioleh text,
rujukan text,
regdate text,
kecamatanl text,
submissiondate text,
propinsi text,
laboratoriumproteinuria text,
laboratoriumhbsag text,
dirujukke text,
highrisklabourreason text,
fetusnumberrisk text,
alergi text,
labcheck text,
laboratoriumthalasemia text,
tbcrisk text,
cardiovasculardiseaserecordrisk text,
tanggallahiribu text,
gakintidak text,
nomortelpon text,
nomortelponhp text,
bbkg text,
integrasiprogramtbtbc text,
fetussizerisk text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.rencana_persalinan (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		village text,
rencanapenolongpersalinan text,
pendonor text,
today text,
tanggal text,
rencanapendampingpersalinan text,
transportasi text,
tempatrencanapersalinan text,
submissiondate text,
address1 text,
htp text,
lokasiperiksa text,
tanggalkunjunganrencanapersalinan text,
lokasiperiksaother text,
kondisirumah text,
persediaanperlengkapanpersalinan text,
ancid text,
cityvillage text,
subvillage text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.kunjungan_anc (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		nomortelponhp text,
trimesterke text,
taksiranberatjanin text,
dirujukke text,
lilacm text,
jumlahjanin text,
ancid text,
anamnesisibu text,
kabupaten text,
pelayanancatatdibukukia text,
registrationdate text,
existinglocation text,
village text,
address1 text,
jumlahfe text,
highrisklabourfetusnumber text,
keterangan text,
hiddenancke text,
lokasiperiksa text,
refdate text,
tanggalhpht text,
hasilpemeriksaanlila text,
rujukan text,
treatment text,
hpht text,
ancke text,
jamkesmas text,
tddiastolik text,
statusgiziibu text,
referencedate text,
djj text,
kepalaterhadapjaninpap text,
pelayananfe text,
submissiondate text,
provinsi text,
statusimunisasitt text,
komplikasilain text,
treatmenttext text,
cityvillage text,
dusun text,
usiaklinis text,
reflekspatelaibu text,
nomortelpon text,
tdsistolik text,
pelayananinjeksitt text,
today text,
regdate text,
highrisklabourfetussize text,
desa text,
nomorhp text,
keterangank1k4who text,
caramasuktempatpelayanan text,
keadaanibusaattiba text,
subdistrict text,
subvillage text,
kecamatan text,
keadaanibusaatpulang text,
tandavitaltdsistolik text,
tfu text,
persentasijanin text,
province text,
district text,
lokasiperiksaother text,
ancdate text,
bbkg text,
komplikasidalamkehamilan text,
dirujukkel text,
highriskpregnancypih text,
highrisklabourfetusmalpresentation text,
lainlain text,
highriskpregnancyproteinenergymalnutrition text,
kunjunganke text,
tandavitaltddiastolik text,
kepalajaninterhadappap text,
pelayanancatatbukukia text,
dirujuk text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.kunjungan_anc_integrasi (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		integrasiprogrammalariaperiksadarah text,
highrisktbc text,
today text,
subvillage text,
lokasiperiksa text,
integrasiprogrampmtctserologi text,
integrasiprogrampmtctarv text,
integrasiprogrampmtctarvprofilaksis text,
submissiondate text,
village text,
integrasiprogrampmtctvct text,
integrasiprogrammalariakelambu text,
integrasiprogramtbdahak text,
highriskmalaria text,
address1 text,
integrasiprogrammalariaobat text,
integrasiprogrammalariakelambuberinsektisida text,
integrasiprogrampmtctperiksadarah text,
integrasiprogramtbobat text,
ancid text,
cityvillage text,
existinglocation text,
lokasiperiksaother text,
referencedate text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.kunjungan_anc_lab_test (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		laboratoriumproteinuria text,
treatmentthalasemiatxt text,
registrationdate text,
subvillage text,
laboratoriumguladarah text,
treatmentdiabetestxt text,
treatmentsifilistxt text,
cityvillage text,
address1 text,
lokasiperiksaother text,
laboratoriumperiksahbanemia text,
laboratoriumhbsag text,
village text,
laboratoriumthalasemia text,
today text,
ancid text,
treatmentanemiatxt text,
regdate text,
lokasiperiksa text,
referencedate text,
treatmentproturintxt text,
highriskpregnancyanemia text,
highriskpregnancydiabetes text,
submissiondate text,
existinglocation text,
treatmenthbsagtxt text,
laboratoriumperiksahbhasil text,
laboratoriumsifilis text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.penutupan_ibu (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		othermaternaldeathcause text,
birthattendant text,
cityvillage text,
address1 text,
closereasonother text,
otherclosereason text,
maternaldeathdate text,
placeofdeath text,
referred text,
iskicloseconfirmed text,
regdate text,
otherplaceofdeath text,
notmaternaldeathcause text,
referrallocation text,
submissiondate text,
village text,
subvillage text,
maternaldeathcause text,
registrationdate text,
existinglocation text,
closereason text,
prereferralmanagement text,
confirmecclose text,
today text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.edit_ibu (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		umur text,
pekerjaan text,
nomortelponhp text,
kabupaten text,
kecamatan text,
puskesmas text,
namalengkap text,
golongandarah text,
submissiondate text,
tanggalregistrasi text,
desa text,
namasuami text,
tglpindah text,
uniqueid text,
nik text,
dusun text,
gakintidak text,
namadukun text,
asuransijiwa text,
lokasiperiksa text,
lokasiperiksaother text,
province text,
subdistrict text,
noibu text,
alamatdomisili text,
pendidikan text,
namakader text,
tanggalperiksa text,
pasienwilayah text,
highriskpregnancyyoungmaternalage text,
highriskpregnancyoldmaternalage text,
tanggallahiribu text,
tanggallahir text,
regdate text,
village text,
district text,
today text,
registrationdate text,
provinsi text,
agama text,
pasienpindahan text,
subvillage text,
posyandu text,
jeniskontrasepsi text,
existinglocation text,
gps text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.update_photo (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		facevector text,
village text,
cityvillage text,
subvillage text,
address1 text,
existinglocation text,
today text,
submissiondate text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.identitas_ibu (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		kabupaten text,
namalengkap text,
tanggallahir text,
alamatdomisili text,
highriskpregnancyyoungmaternalage text,
regdate text,
existinglocation text,
tglpindah text,
submissiondate text,
pasienpindahan text,
namasuami text,
puskesmas text,
nik text,
district text,
subvillage text,
umur text,
registrationdate text,
tanggalregistrasi text,
lokasiperiksa text,
desa text,
pekerjaan text,
asuransijiwa text,
golongandarah text,
nomortelponhp text,
today text,
province text,
dusun text,
uniqueid text,
village text,
tanggallahiribu text,
pendidikan text,
posyandu text,
gps text,
pasienwilayah text,
namadukun text,
highriskpregnancyoldmaternalage text,
jeniskontrasepsi text,
tanggalperiksa text,
provinsi text,
kecamatan text,
noibu text,
agama text,
gakintidak text,
namakader text,
lokasiperiksaother text,
subdistrict text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.penutupan_pnc (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		othermaternaldeathcause text,
placeofdeath text,
notmaternaldeathcause text,
ispnccloseconfirmed text,
cityvillage text,
subvillage text,
address1 text,
existinglocation text,
otherplaceofdeath text,
today text,
village text,
submissiondate text,
registrationdate text,
ancid text,
pncclosereason text,
deathdate text,
maternaldeathcause text,
confirmpncclose text,
regdate text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.dokumentasi_persalinan (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		persalinan text,
manajemenaktifkalaiii text,
alamatbersalin text,
dirujukke text,
highriskpostpartumhemorrhage text,
referencedate text,
village text,
integrasiprogram text,
komplikasilainlain text,
keadaanbayi text,
highriskpostpartumsectiocaesaria text,
ancid text,
address1 text,
hpht text,
penolong text,
highriskpostpartumdistosia text,
highriskpostpartumforceps text,
kepemilikanbukukia text,
today text,
lokasiperiksa text,
tanggalhpht text,
usiakehamilan text,
tanggalplasentalahir text,
dirujukkelainlain text,
submissiondate text,
keadaanibu text,
jamkalaiaktif text,
jamkalaii text,
persentasi text,
tempat text,
penolonglainlain text,
pelayanan text,
highriskpostpartumpih text,
cityvillage text,
tanggalkalaiaktif text,
perdarahankalaiv2jampostpartum text,
highriskpostpartummaternalsepsis text,
highriskpostpartumeclampsia text,
highriskpostpartumvacum text,
carapersalinanibu text,
highriskpostpartuminfection text,
highriskpostpartumpreeclampsia text,
treatmenttext text,
subvillage text,
existinglocation text,
tanggalkalaii text,
highriskpostpartumpreeclampsiaeclampsia text,
treatment text,
jamplasentalahir text,
tempatbersalin text,
komplikasi text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.pnc_edit (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		hpht text,
tanggalkalaii text,
perdarahankalaiv2jampostpartum text,
penolonglainlainln text,
regdate text,
keadaanibu text,
komplikasi text,
usiakehamilan text,
jamkalaii text,
carapersalinanibu text,
integrasiprogram text,
tempatbersalin text,
dirujukke text,
dirujukkelainlain text,
pelayanan text,
today text,
submissiondate text,
penolong text,
manajemenaktifkalaiii text,
jamkalaiaktif text,
persentasi text,
komplikasilainlain text,
alamatbersalin text,
kepemilikanbukukia text,
registrationdate text,
keadaanbayi text,
persalinan text,
tanggalkalaiaktif text,
tanggalplasentalahir text,
jamplasentalahir text,
penolonglainlain text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.post_partum_kb (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		ancid text,
existinglocation text,
rencana text,
pelaksanaanbawah42hari text,
pelaksanaank42hari text,
village text,
subvillage text,
metodekontrasepsi text,
today text,
submissiondate text,
cityvillage text,
address1 text,
pelaksanaanatas42hari text,
registrationdate text,
pelaksanaanl42hari text,
regdate text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.register_pnc_oa (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		district text,
subvillage text,
namalengkap text,
subdistrict text,
keadaanibu text,
persentasi text,
highriskpregnancyyoungmaternalage text,
highriskchildlowbirthweght text,
highriskpostpartumforceps text,
highriskpostpartumsectiocaesaria text,
today text,
uniqueid text,
golongandarah text,
keadaanbayi text,
dirujukkelainlain text,
nik text,
posyandu text,
namadukun text,
submissiondate text,
agama text,
province text,
puskesmas text,
noibu text,
perdarahankalaiv2jampostpartum text,
komplikasi text,
highriskpregnancyoldmaternalage text,
village text,
namakader text,
tanggalkalaiaktif text,
jamkalaiaktif text,
tanggalkalaii text,
pelayanan text,
komplikasilainlain text,
highriskpostpartuminfection text,
namasuami text,
usiakehamilan text,
jamplasentalahir text,
tempatbersalin text,
alamatbersalin text,
tanggallahiranak text,
gakintidak text,
asuransijiwa text,
nomortelponhp text,
persalinan text,
jamkalaii text,
tempat text,
manajemenaktifkalaiii text,
namabayi text,
dusun text,
highriskpostpartumpih text,
highriskpostpartumpreeclampsiaeclampsia text,
highriskpostpartumdistosia text,
provinsi text,
penolonglainlain text,
lokasiperiksa text,
pekerjaan text,
pptest text,
dirujukke text,
pendidikan text,
umur text,
integrasiprogram text,
jeniskelamin text,
highriskpostpartumvacum text,
registrationdate text,
tanggallahir text,
hpht text,
beratlahir text,
penolong text,
nobayi text,
tanggallahiribu text,
tanggalplasentalahir text,
carapersalinanibu text,
highriskpostpartumhemorrhage text,
highriskpostpartummaternalsepsis text,
beratbayi text,
desa text,
highriskchildpreterm text,
regdate text,
kabupaten text,
alamatdomisili text,
kecamatan text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.kunjungan_pnc (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		integrasiprogramfotothorax text,
treatment text,
cityvillage text,
subvillage text,
nik text,
integrasiprogramantitb text,
highriskpostpartummaternalsepsis text,
village text,
tanggallahiranak text,
tandavitaltddiastolik text,
highriskpostpartuminfection text,
daruratnifas text,
rujukan text,
keadaanpulang text,
tandavitalsuhu text,
pelayananfe text,
integrasiprogramantimalaria text,
komplikasilainnya text,
vitamina2jampp text,
dirujukkelainnya text,
highriskpostpartummastitis text,
regdate text,
treatmenttext text,
highriskpostpartumpih text,
lokasiperiksa text,
pncdate text,
harikekf text,
tandavitaltdsistolik text,
registrationdate text,
tanggalkunjungan text,
keadaantiba text,
highriskpostpartumdistosia text,
submissiondate text,
kondisipascatindakan text,
dirujukke text,
keterangan text,
existinglocation text,
lokasiperiksaother text,
vitamina24jampp text,
komplikasi text,
today text,
ancid text,
address1 text,
penanganannifas text,
highriskpostpartumhemorrhage text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.penutupan_anak (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		today text,
confirmchildclose text,
existinglocation text,
childdeathcauseother text,
placeofdeath text,
prereferralmanagement text,
referred text,
referrallocation text,
submissiondate text,
closereason text,
desaanak text,
existingsubvillage text,
village text,
childdeathcause text,
subvillage text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.kunjungan_balita (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		dirujukkebayi text,
babyage text,
tanggalpemeriksaananakbalita text,
statussesehatanbayi text,
today text,
indikatorberatbadanbayi text,
hasildilakukannyakpsp text,
kpsppenyimpangan text,
beratbayi text,
tanggalkunjunganbayiperbulan text,
hasilpengukurantinggianakbalita text,
statusgizi text,
mtbs text,
dirujukkelainnyabayi text,
existinglocation text,
lokasiperiksa text,
panjangbayi text,
pemberianasieksklusif text,
penyakit text,
village text,
hasilpenimbangananakbalita text,
kunjunganbayike text,
lokasiperiksaother text,
asiaksklusif text,
pelayananvita text,
statuskesehatanbayi text,
rujukanbayi text,
desaanak text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.balita_kunjungan (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		lokasiperiksa text,
b05010 text,
tanggalkunjunganbayiperbulan text,
b05011 text,
pemberianvitadankondisibalitasaatsakit text,
beratbadanbayisetiapkunjunganbayiperbulan text,
b05012 text,
hasildilakukannyakpsp text,
b01004 text,
today text,
submissiondate text,
regdate text,
registrationdate text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.edit_bayi (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		ibuentityid text,
kepemilikanbukukia text,
beratbadansaatlahir text,
beratlahir text,
existinglocation text,
nobayi text,
desaanak text,
referencedate text,
ibucaseid text,
namabayi text,
childexistinglocation text,
today text,
submissiondate text,
tanggallahir text,
tanggallahiranak text,
jeniskelamin text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.imunisasi_bayi (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		polio4 text,
today text,
desaanak text,
lokasiperiksa text,
polio1 text,
polio3 text,
village text,
polio2 text,
ipv text,
campaklanjutan text,
childexistinglocation text,
hb0 text,
dpthb1 text,
campak text,
dpthblanjutan text,
subvillage text,
bcg text,
dpthb2 text,
dpthb3 text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.kohort_kunjungan_bayi_perbulan (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		desaanak text,
tanggalkunjunganbayiperbulan text,
lokasiperiksa text,
lokasiperiksaother text,
subvillage text,
pemberianasieksklusif text,
statusgizi text,
submissiondate text,
beratbayi text,
pelayananvita text,
mtbs text,
rujukanbayi text,
dirujukkebayi text,
today text,
village text,
beratbadanbayisetiapkunjunganbayiperbulan text,
hasildilakukannyakpsp text,
kpsppenyimpangan text,
statuskesehatanbayi text,
existinglocation text,
babyage text,
kunjunganbayike text,
panjangbayi text,
indikatorberatbedanbayi text,
indikatorberatbadanbayi text,
penyakit text,
asiaksklusif text,
dirujukkelainnyabayi text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.kunjungan_neonatal (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		desaanak text,
beratbayi text,
dirujukkeneonatal text,
highriskchilditerus text,
panjangbayi text,
rujukanneonatal text,
subvillage text,
tanggallahir text,
tanggallahiranak text,
neonatal text,
kunjunganneonatal text,
tanggalkunjunganbayiperbulan text,
komplikasineonataltertangani text,
dirujukkelainnyaneonatal text,
confirmofdeath text,
highriskchildhypothermia text,
highriskchildneonatalsepsis text,
kondisibayi text,
today text,
tanggalkunjunganneonatal text,
komplikasineonatal text,
komplikasineonatallain text,
highriskchildbirthtrauma text,
submissiondate text,
regdate text,
suhubayi text,
frekuensinapas text,
frekuensidenyutjantung text,
registrationdate text,
existinglocation text,
jenispelayanan text,
hb0 text,
village text,
pemberianimunisasihb text,
highriskchildasphyxia text,
highriskchildcongenitalabnormality text,
highriskchildinfection text,
highriskchildtetanusneonatorum text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.tambah_bayi (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		deviceid text,
subdistrict text,
cityvillage text,
provinsi text,
kabupaten text,
today text,
phonenumber text,
generatednotename13 text,
generatednotename14 text,
dusun text,
tanggalpendaftaran text,
province text,
subvillage text,
existinglocation text,
desa text,
kecamatan text,
instanceid text,
simserial text,
district text,
village text,
address1 text,
tanggalperiksa text,
lokasiperiksa text,
lokasiperiksaother text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.register_bayi_oa (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		highriskpregnancyyoungmaternalage text,
subdistrict text,
kecamatan text,
highriskpregnancyoldmaternalage text,
noibu text,
namalengkap text,
nobayi text,
jeniskelamin text,
submissiondate text,
registrationdate text,
village text,
district text,
highriskchildlowbirthweght text,
today text,
uniqueid text,
provinsi text,
desa text,
subvillage text,
dusun text,
namabayi text,
tanggallahiranak text,
highrisklowbirthweight text,
kabupaten text,
namasuami text,
alamatdomisili text,
beratlahir text,
province text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.penutupan_kb (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		confirmkbclose text,
cityvillage text,
subvillage text,
keterangangagal text,
kbclosereason text,
deathdate text,
jeniskontrasepsi text,
submissiondate text,
address1 text,
iskbcloseconfirmed text,
today text,
registrationdate text,
village text,
keterangando text,
regdate text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.tambah_kb (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		namalengkap text,
subdistrict text,
provinsi text,
alkipenyakitkronis text,
regdate text,
subvillage text,
address1 text,
tanggalperiksa text,
tddiastolik text,
submissiondate text,
province text,
kabupaten text,
tanggallahir text,
umur text,
tdsistolik text,
jeniskontrasepsi text,
lokasiperiksaother text,
tanggallahiribu text,
alkilila text,
today text,
existinglocation text,
village text,
dusun text,
tanggalkunjungan text,
cityvillage text,
paritas text,
alkihb text,
registrationdate text,
alkipenyakitims text,
district text,
kecamatan text,
desa text,
lokasiperiksa text,
keterangantentangpesertakb text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.edit_tambah_kb (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		alkilila text,
keterangantentangpesertakb text,
regdate text,
subdistrict text,
dusun text,
submissiondate text,
alkipenyakitims text,
today text,
village text,
tanggalperiksa text,
paritas text,
registrationdate text,
namalengkap text,
existinglocation text,
provinsi text,
desa text,
lokasiperiksa text,
district text,
address1 text,
tanggalkunjungan text,
tdsistolik text,
alkipenyakitkronis text,
province text,
subvillage text,
kabupaten text,
tanggallahiribu text,
tddiastolik text,
alkihb text,
jeniskontrasepsi text,
lokasiperiksaother text,
tanggallahir text,
umur text,
cityvillage text,
kecamatan text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.tambah_kb_oa (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		pendidikan text,
namakader text,
alkipenyakitkronis text,
ishighrisk text,
submissiondate text,
regdate text,
nik text,
village text,
lokasiperiksa text,
desa text,
umur text,
posyandu text,
tdsistolik text,
today text,
tanggalkunjungan text,
pekerjaan text,
golongandarah text,
alkihb text,
alkipenyakitims text,
jeniskontrasepsi text,
provinsi text,
noibu text,
nomortelponhp text,
pptest text,
tddiastolik text,
paritas text,
alkilila text,
jeniskontrasepsiyangdigunakan text,
kabupaten text,
registrationdate text,
kecamatan text,
dusun text,
gakintidak text,
tooyoungrisk text,
district text,
uniqueid text,
namalengkap text,
tanggallahir text,
alamatdomisili text,
keterangantentangpesertakb text,
highrisknote text,
subdistrict text,
tanggallahiribu text,
namadukun text,
asuransijiwa text,
toooldmother text,
subvillage text,
puskesmas text,
namasuami text,
agama text,
province text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.kohort_pelayanan_kb (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		today text,
keterangantentangpesertakb text,
jeniskontrasepsiyangdigunakan text,
keterangantentangpesertakb2 text,
subvillage text,
address1 text,
existinglocation text,
lokasiperiksa text,
submissiondate text,
regdate text,
registrationdate text,
village text,
cityvillage text,
keteranganganticara text,
keterangankomplikasi text,
tanggalkunjungan text,
jeniskontrasepsi text,
keteranganefeksamping text);
---------------------------------------
