CREATE TABLE IF NOT EXISTS sid3.blood_test (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		district text,
sub_village text,
existinglocation text,
province text,
sub_district text,
tandavitaltdsistolik text,
tandavitaltddiastolik text,
pulse text,
ahr text,
submissiondate text,
village text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.coaching_feedback_form (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		masalah text,
penggunaanlangsungsaatkunjungan text,
tidakdapatmemasukkandatatertenturegisteranc text,
rentangdatavariabeltidaksesuairegisterpnc text,
pilihanvariabelyangadatidaksesuaikohortanak text,
kalkulasivariabeltidaksesuaikohortanak text,
pilihanvariabelyangadatidaksesuairegisteranc text,
rentangdatavariabeltidaksesuairegisteranc text,
masalahbaterai text,
pengisidayarusaktidakberfungsi text,
masalahlainnyapenggunaanlangsung text,
datavariabelyangdimasukkanhilangkartuibu text,
pilihanvariabelyangadatidaksesuaikohortkb text,
tidakdapatmemasukkandatatertentukohortkb text,
koneksiinternet text,
formentriregisterpnc text,
masalahregisterpnc text,
username text,
bateraicepathabis text,
tidakdapatmengeditdatakohortkb text,
keteranganumpanbaliklainnya text,
tidakdapatlogin text,
baterai text,
rentangdatavariabeltidaksesuaikartuibu text,
masalahkohortkb text,
masalahlainnyakohortanak text,
masalahkartuibu text,
kalkulasivariabeltidaksesuairegisteranc text,
masalahkohortanak text,
aplikasierror text,
formentrikartuibu text,
tidakdapatmemasukkandatatertentukartuibu text,
formentrikohortkb text,
datavariabelyangdimasukkanhilangregisterpnc text,
datayangditampilkantidaksesuaidenganyangdimasukkanregisterpnc text,
respondentname text,
kuotainternettelahhabis text,
masalahlainnyakoneksiinternet text,
masalahlainnyaaplikasierror text,
masalahlainnyakartuibu text,
datayangditampilkantidaksesuaidenganyangdimasukkankohortkb text,
formentrikohortanak text,
tidakdapatmemasukkandatatertentukohortanak text,
umpanbaliklainnya text,
masalahlainnyapenggunaanaplikasi text,
kalkulasivariabeltidaksesuaikartuibu text,
tidakdapatmengeditdataregisteranc text,
tidakdapatmengeditdatakohortanak text,
submissiondate text,
masalahkoneksiinternet text,
koneksiinternetdiposyandulemah text,
formentriregisteranc text,
masalahregisteranc text,
datavariabelyangdimasukkanhilangkohortanak text,
datayangditampilkantidaksesuaidenganyangdimasukkankohortanak text,
kalkulasivariabeltidaksesuairegisterpnc text,
tidakdapatmengeditdataregisterpnc text,
tablettiba_tibamati text,
masalahaplikasierror text,
pilihanvariabelyangadatidaksesuaikartuibu text,
masalahlainnyakohortkb text,
masalahlainnyaregisteranc text,
pilihanvariabelyangadatidaksesuairegisterpnc text,
coachingdate text,
pengunaanaplikasi text,
rentangdatavariabeltidaksesuaikohortanak text,
waktuloadingformlama text,
waktumenyimpanformlama text,
responlayarsentuhlama text,
masalahsinkronisasidata text,
datavariabelyangdimasukkanhilangregisteranc text,
datayangditampilkantidaksesuaidenganyangdimasukkanregisteranc text,
pengisianbaterailama text,
masalahpenggunaanlangsungsaatkunjungan text,
aplikasimenutupsendiri text,
datavariabelyangdimasukkanhilangkohortkb text,
masalahlainnyaregisterpnc text,
bidanid text,
koneksiinternetdipolindespuskesmaslemah text,
masalahlainnyabaterai text,
masalahpenggunaanaplikasi text,
tidakdapatmengeditdatakartuibu text,
kalkulasivariabeltidaksesuaikohortkb text,
datayangditampilkantidaksesuaidenganyangdimasukkankartuibu text,
rentangdatavariabeltidaksesuaikohortkb text,
tidakdapatmemasukkandatatertenturegisterpnc text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.penutupan_anc (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		maternaldeathcause text,
placeofdeath text,
notematernaldeathcause text,
hasancleftplace text,
cityvillage text,
sub_village text,
existinglocation text,
desa text,
closereason text,
otherclosereason text,
address text,
isanccloseconfirmed text,
referred text,
referrallocation text,
submissiondate text,
othermaternaldeathcause text,
otherplaceofdeath text,
birthattendant text,
prereferralmanagement text,
dusun text,
maternaldeathdate text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.edit_anc (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		gravida text,
persalinansebelumnya text,
riwayatkomplikasikebidanan text,
tanggalmemperolehbukukia text,
partus text,
htp text,
submissiondate text,
alergi text,
jamkesmas text,
registrationdate text,
referencedate text,
abortus text,
hidup text,
penyakitkronis text,
tbcm text,
bbkg text,
hasilpemeriksaanlila text,
rkklainnya text,
rpklainnya text,
tanggalhpht text,
trimesterke text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.tambah_anc (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		partus text,
usiaklinis text,
registrationdate text,
lokasiperiksaother text,
provinsi text,
ancid text,
persalinansebelumnya text,
highrisktuberculosis text,
highriskhivaids text,
pptest text,
tbcm text,
malariarisk text,
highrisklabourtbrisk text,
otherriskcongenitalabnormality text,
desa text,
tanggalhpht text,
hasilpemeriksaanlila text,
highriskdidneydisorder text,
district text,
kecamatan text,
hidup text,
trimesterke text,
highriskstibbvs text,
otherriskearlywaterbreak text,
existinglocation text,
province text,
abortus text,
riwayatkomplikasikebidanan text,
otherriskmolahidatidosa text,
dusun text,
gravida text,
highriskpregnancyabortus text,
highriskmalaria text,
address1 text,
rkklainnya text,
bbkg text,
highriskpregnancyproteinenergymalnutrition text,
highriskpregnancytoomanychildren text,
highriskectopicpregnancy text,
type text,
highrisklaboursectioncesarearecord text,
submissiondate text,
sub_district text,
htp text,
highriskheartdisorder text,
lokasiperiksa text,
cityvillage text,
referencedate text,
tanggallahiranaksebelumnya text,
penyakitkronis text,
rpklainnya text,
tanggalmemperolehbukukia text,
kabupaten text,
alergi text,
jamkesmas text,
highriskcardiovasculardiseaserecord text,
highriskasthma text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.register_anc (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		dirujukke text,
fetussizerisk text,
ishighrisk text,
kecamatan text,
programintegration text,
integrasiprogramtbdahak text,
keterangan text,
anemiarisk text,
tbrisk text,
toomanychildrenrisk text,
earlywaterbreakrisk text,
bbsebelumhamil text,
laboratoriumhbsag text,
integrasiprogrammalariaobat text,
integrasiprogramtbobat text,
molahidatidosarisk text,
puskesmas text,
tanggalhpht text,
pihrisk text,
agama text,
jamkesmas text,
umur text,
gravida text,
trimesterke text,
jumlahjanin text,
pelayanancatatdibukukia text,
lainlain text,
namasuami text,
kelainanbentuk text,
persalinansebelumnya text,
tanggalmemperolehbukukia text,
hasilpemeriksaanlila text,
resikoterdeteksipertamakalioleh text,
desa text,
pekerjaan text,
pelayananfe text,
laboratoriumperiksahbdilakukan text,
integrasiprogrampmtctserologi text,
submissiondate text,
htp text,
pelayananinjeksitt text,
proteinenergymalnutritionrisk text,
telponmemilikitidak text,
abortus text,
malariarisk text,
highrisknote text,
keadaanibusaattiba text,
fetusmalpresentationrisk text,
fetusnumberrisk text,
heartdisorderrisk text,
gakintidak text,
kepalajaninterhadappap text,
asuransijiwa text,
partus text,
reflekspatelaibu text,
highrisklabourreason text,
pendidikan text,
namadukun text,
alergi text,
labcheck text,
namakader text,
rpklainnya text,
kronis text,
bbkg text,
tandavitaltdsistolik text,
tooyoungrisk text,
zectioncesarearecordrisk text,
congenitalabnormalityrisk text,
noibu text,
dusun text,
integrasiprogramtbtbc text,
diabetesrisk text,
kabupaten text,
taksiranberatjanin text,
nomortelponhp text,
tbcrisk text,
ishighriskpregnancy text,
referencedate text,
kecamatanl text,
integrasiprogrammalariakelambuberinsektisida text,
komplikasidalamkehamilan text,
cardiovasculardiseaserecordrisk text,
ishighrisklabour text,
laboratoriumperiksahbhasil text,
integrasiprogrammalariaperiksadarah text,
laboratoriumthalasemia text,
integrasiprogrammalariamalaria text,
rujukan text,
kidneydisorderrisk text,
tandavitaltddiastolik text,
laboratoriumproteinuria text,
laboratoriumguladarah text,
stibbvsrisk text,
rkklainnya text,
integrasiprogrampmtctvct text,
tuberculosisrisk text,
hivaidsrisk text,
registrationdate text,
rkk text,
ancke text,
ishighriskreason text,
isotherrisk text,
riwayatkomplikasikebidanan text,
keadaanibusaatpulang text,
djj text,
tanggallahir text,
alamatdomisili text,
ectopicpregnancyrisk text,
anamnesisibu text,
abortusrisk text,
asthmarisk text,
highriskpregnancyreason text,
persentasijanin text,
integrasiprogrampmtctperiksadarah text,
hidup text,
penyakitkronis text,
bukukia text,
statusimunisasitt text,
laboratoriumsifilis text,
otherriskreason text,
namalengkap text,
golongandarah text,
posyandu text,
tbcm text,
statusgiziibu text,
tfu text,
laboratoriumperiksahbanemia text,
integrasiprogrampmtctarvprofilaksis text,
propinsi text,
caramasuktempatpelayanan text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.rencana_persalinan (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		transportasi text,
tanggalkunjunganrencanapersalinan text,
lokasiperiksa text,
tempatrencanapersalinan text,
rencanapendampingpersalinan text,
submissiondate text,
ancid text,
address1 text,
lokasiperiksaother text,
persediaanperlengkapanpersalinan text,
cityvillage text,
rencanapenolongpersalinan text,
pendonor text,
kondisirumah text,
htp text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.kunjungan_anc (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		desa text,
nomorhp text,
referencedate text,
komplikasilain text,
dirujukke text,
province text,
kecamatan text,
tanggalhpht text,
jamkesmas text,
caramasuktempatpelayanan text,
anamnesisibu text,
tfu text,
highriskpregnancyproteinenergymalnutrition text,
address1 text,
dusun text,
submissiondate text,
registrationdate text,
pelayanancatatdibukukia text,
pelayananfe text,
treatment text,
treatmenttext text,
highrisklabourfetussize text,
ancdate text,
kepalajaninterhadappap text,
keterangan text,
komplikasidalamkehamilan text,
cityvillage text,
tandavitaltdsistolik text,
usiaklinis text,
statusimunisasitt text,
keadaanibusaatpulang text,
hiddenancke text,
ancid text,
existinglocation text,
sub_district text,
ancke text,
highriskpregnancypih text,
district text,
lainlain text,
taksiranberatjanin text,
nomortelpon text,
bbkg text,
pelayananinjeksitt text,
highrisklabourfetusmalpresentation text,
trimesterke text,
tandavitaltddiastolik text,
statusgiziibu text,
keadaanibusaattiba text,
lokasiperiksaother text,
keterangank1k4who text,
lokasiperiksa text,
jumlahjanin text,
reflekspatelaibu text,
djj text,
persentasijanin text,
provinsi text,
kunjunganke text,
rujukan text,
highrisklabourfetusnumber text,
kabupaten text,
hasilpemeriksaanlila text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.kunjungan_anc_integrasi (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		existinglocation text,
integrasiprogrammalariaobat text,
integrasiprogrammalariakelambuberinsektisida text,
highriskmalaria text,
submissiondate text,
cityvillage text,
lokasiperiksa text,
integrasiprogrampmtctperiksadarah text,
highrisktbc text,
ancid text,
lokasiperiksaother text,
integrasiprogrampmtctserologi text,
integrasiprogramtbdahak text,
integrasiprogrammalariaperiksadarah text,
integrasiprogramtbobat text,
address1 text,
referencedate text,
integrasiprogrampmtctvct text,
integrasiprogrampmtctarvprofilaksis text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.kunjungan_anc_lab_test (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		treatmentproturintxt text,
treatmentdiabetestxt text,
laboratoriumthalasemia text,
lokasiperiksa text,
laboratoriumperiksahbanemia text,
treatmentanemiatxt text,
laboratoriumsifilis text,
treatmenthbsagtxt text,
highriskpregnancydiabetes text,
ancid text,
lokasiperiksaother text,
referencedate text,
laboratoriumperiksahbhasil text,
treatmentthalasemiatxt text,
cityvillage text,
address1 text,
existinglocation text,
laboratoriumproteinuria text,
laboratoriumguladarah text,
treatmentsifilistxt text,
laboratoriumhbsag text,
highriskpregnancyanemia text,
submissiondate text,
registrationdate text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.penutupan_ibu (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		cityvillage text,
placeofdeath text,
otherplaceofdeath text,
referred text,
iskicloseconfirmed text,
existinglocation text,
maternaldeathdate text,
notmaternaldeathcause text,
othermaternaldeathcause text,
prereferralmanagement text,
referrallocation text,
registrationdate text,
address1 text,
closereason text,
otherclosereason text,
maternaldeathcause text,
birthattendant text,
submissiondate text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.edit_ibu (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		tglpindah text,
nik text,
dusun text,
namalengkap text,
namasuami text,
umur text,
pendidikan text,
namakader text,
submissiondate text,
tanggalregistrasi text,
lokasiperiksa text,
kabupaten text,
existinglocation text,
lokasiperiksaother text,
uniqueid text,
agama text,
namadukun text,
pasienpindahan text,
sub_village text,
alamatdomisili text,
posyandu text,
asuransijiwa text,
golongandarah text,
nomortelponhp text,
provinsi text,
gakintidak text,
jeniskontrasepsi text,
district text,
tanggallahir text,
gps text,
province text,
kecamatan text,
puskesmas text,
noibu text,
registrationdate text,
pasienwilayah text,
village text,
sub_district text,
desa text,
pekerjaan text,
highriskpregnancyyoungmaternalage text,
highriskpregnancyoldmaternalage text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.update_photo (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		facevector text,
cityvillage text,
address1 text,
existinglocation text,
submissiondate text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.identitas_ibu (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		sub_district text,
pendidikan text,
jeniskontrasepsi text,
pasienwilayah text,
uniqueid text,
village text,
tanggallahir text,
asuransijiwa text,
golongandarah text,
submissiondate text,
tglpindah text,
province text,
pekerjaan text,
gakintidak text,
pasienpindahan text,
puskesmas text,
namalengkap text,
namasuami text,
umur text,
alamatdomisili text,
namakader text,
gps text,
desa text,
agama text,
posyandu text,
district text,
provinsi text,
kabupaten text,
highriskpregnancyyoungmaternalage text,
sub_village text,
noibu text,
namadukun text,
highriskpregnancyoldmaternalage text,
existinglocation text,
lokasiperiksa text,
lokasiperiksaother text,
nik text,
dusun text,
kecamatan text,
nomortelponhp text,
registrationdate text,
tanggalregistrasi text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.penutupan_pnc (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		deathdate text,
ispnccloseconfirmed text,
submissiondate text,
ancid text,
existinglocation text,
placeofdeath text,
notmaternaldeathcause text,
pncclosereason text,
othermaternaldeathcause text,
cityvillage text,
address1 text,
maternaldeathcause text,
otherplaceofdeath text,
registrationdate text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.dokumentasi_persalinan (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		referencedate text,
perdarahankalaiv2jampostpartum text,
highriskpostpartumpih text,
highriskpostpartumvacum text,
treatment text,
treatmenttext text,
kepemilikanbukukia text,
submissiondate text,
cityvillage text,
keadaanibu text,
tanggalplasentalahir text,
integrasiprogram text,
komplikasilainlain text,
dirujukke text,
tanggalkalaiaktif text,
tanggalkalaii text,
carapersalinanibu text,
manajemenaktifkalaiii text,
komplikasi text,
highriskpostpartumhemorrhage text,
address1 text,
tanggalhpht text,
jamkalaii text,
persentasi text,
tempatbersalin text,
penolong text,
highriskpostpartumpreeclampsiaeclampsia text,
ancid text,
jamkalaiaktif text,
alamatbersalin text,
highriskpostpartuminfection text,
persalinan text,
pelayanan text,
highriskpostpartumdistosia text,
usiakehamilan text,
jamplasentalahir text,
penolonglainlain text,
highriskpostpartummaternalsepsis text,
highriskpostpartumforceps text,
existinglocation text,
lokasiperiksa text,
keadaanbayi text,
dirujukkelainlain text,
highriskpostpartumsectiocaesaria text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.pnc_edit (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		penolonglainlain text,
carapersalinanibu text,
integrasiprogram text,
dirujukkelainlain text,
registrationdate text,
tanggalkalaiaktif text,
tanggalplasentalahir text,
tempatbersalin text,
manajemenaktifkalaiii text,
komplikasilainlain text,
alamatbersalin text,
submissiondate text,
keadaanibu text,
tanggalkalaii text,
kepemilikanbukukia text,
jamkalaiaktif text,
jamkalaii text,
jamplasentalahir text,
komplikasi text,
usiakehamilan text,
persalinan text,
dirujukke text,
hpht text,
perdarahankalaiv2jampostpartum text,
penolong text,
pelayanan text,
keadaanbayi text,
persentasi text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.post_partum_kb (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		metodekontrasepsi text,
rencana text,
pelaksanaank42hari text,
ancid text,
existinglocation text,
pelaksanaanl42hari text,
submissiondate text,
registrationdate text,
cityvillage text,
address1 text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.register_pnc_oa (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		dirujukke text,
highriskpregnancyoldmaternalage text,
highriskpostpartumsectiocaesaria text,
province text,
namasuami text,
namakader text,
penolonglainlain text,
jeniskelamin text,
pendidikan text,
beratlahir text,
jamkalaii text,
asuransijiwa text,
persalinan text,
highriskchildlowbirthweght text,
keadaanbayi text,
dirujukkelainlain text,
highriskchildpreterm text,
dusun text,
alamatdomisili text,
pptest text,
highriskpostpartumvacum text,
posyandu text,
penolong text,
highriskpostpartumpreeclampsiaeclampsia text,
nomortelponhp text,
usiakehamilan text,
tanggalkalaii text,
persentasi text,
carapersalinanibu text,
provinsi text,
pekerjaan text,
gakintidak text,
highriskpostpartumhemorrhage text,
highriskpostpartumforceps text,
jamkalaiaktif text,
manajemenaktifkalaiii text,
pelayanan text,
highriskpostpartummaternalsepsis text,
uniqueid text,
sub_district text,
tanggallahir text,
nik text,
alamatbersalin text,
komplikasi text,
sub_village text,
golongandarah text,
keadaanibu text,
village text,
district text,
namabayi text,
tanggallahiranak text,
registrationdate text,
puskesmas text,
integrasiprogram text,
nobayi text,
agama text,
submissiondate text,
desa text,
tanggalkalaiaktif text,
highriskpregnancyyoungmaternalage text,
perdarahankalaiv2jampostpartum text,
tempatbersalin text,
komplikasilainlain text,
highriskpostpartumpih text,
highriskpostpartuminfection text,
kecamatan text,
namadukun text,
tanggalplasentalahir text,
umur text,
jamplasentalahir text,
namalengkap text,
hpht text,
highriskpostpartumdistosia text,
lokasiperiksa text,
kabupaten text,
noibu text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.kunjungan_pnc (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		vitamina2jampp text,
komplikasi text,
dirujukke text,
cityvillage text,
integrasiprogramantimalaria text,
integrasiprogramfotothorax text,
daruratnifas text,
kondisipascatindakan text,
registrationdate text,
highriskpostpartummastitis text,
submissiondate text,
lokasiperiksaother text,
tandavitalsuhu text,
pelayananfe text,
penanganannifas text,
highriskpostpartumpih text,
highriskpostpartumhemorrhage text,
harikekf text,
treatmenttext text,
rujukan text,
dirujukkelainnya text,
keadaanpulang text,
existinglocation text,
lokasiperiksa text,
tandavitaltddiastolik text,
treatment text,
keterangan text,
pncdate text,
tandavitaltdsistolik text,
vitamina24jampp text,
highriskpostpartumdistosia text,
highriskpostpartuminfection text,
highriskpostpartummaternalsepsis text,
keadaantiba text,
ancid text,
address1 text,
nik text,
tanggallahiranak text,
integrasiprogramantitb text,
komplikasilainnya text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.penutupan_anak (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		existingsub_village text,
closereason text,
childdeathcause text,
submissiondate text,
confirmchildclose text,
existinglocation text,
desaanak text,
childdeathcauseother text,
placeofdeath text,
prereferralmanagement text,
referred text,
referrallocation text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.kunjungan_balita (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		panjangbayi text,
pelayananvita text,
dirujukkelainnyabayi text,
today text,
lokasiperiksaother text,
existinglocation text,
indikatorberatbadanbayi text,
penyakit text,
dirujukkebayi text,
desaanak text,
lokasiperiksa text,
babyage text,
kunjunganbayike text,
beratbayi text,
asiaksklusif text,
kpsppenyimpangan text,
statussesehatanbayi text,
tanggalkunjunganbayiperbulan text,
mtbs text,
hasildilakukannyakpsp text,
rujukanbayi text,
statusgizi text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.balita_kunjungan (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		tanggalkunjunganbayiperbulan text,
beratbadanbayisetiapkunjunganbayiperbulan text,
hasildilakukannyakpsp text,
pemberianvitadankondisibalitasaatsakit text,
submissiondate text,
registrationdate text,
lokasiperiksa text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.edit_bayi (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		submissiondate text,
jeniskelamin text,
desaanak text,
childexistinglocation text,
beratlahir text,
existinglocation text,
referencedate text,
ibucaseid text,
nobayi text,
namabayi text,
tanggallahiranak text,
kepemilikanbukukia text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.imunisasi_bayi (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		campak text,
dpthblanjutan text,
today text,
desaanak text,
hb0 text,
polio1 text,
polio2 text,
sub_village text,
lokasiperiksa text,
bcg text,
dpthb2 text,
campaklanjutan text,
polio4 text,
ipv text,
childexistinglocation text,
dpthb1 text,
polio3 text,
dpthb3 text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.kohort_kunjungan_bayi_perbulan (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		sub_village text,
existinglocation text,
babyage text,
indikatorberatbadanbayi text,
statusgizi text,
kpsppenyimpangan text,
penyakit text,
rujukanbayi text,
submissiondate text,
kunjunganbayike text,
beratbayi text,
hasildilakukannyakpsp text,
pelayananvita text,
lokasiperiksaother text,
asiaksklusif text,
dirujukkebayi text,
dirujukkelainnyabayi text,
desaanak text,
tanggalkunjunganbayiperbulan text,
lokasiperiksa text,
panjangbayi text,
statuskesehatanbayi text,
mtbs text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.kunjungan_neonatal (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		rujukanneonatal text,
highriskchildinfection text,
highriskchildtetanusneonatorum text,
tanggallahiranak text,
panjangbayi text,
frekuensidenyutjantung text,
hb0 text,
dirujukkeneonatal text,
sub_village text,
suhubayi text,
dirujukkelainnyaneonatal text,
confirmofdeath text,
highriskchilditerus text,
highriskchildasphyxia text,
highriskchildbirthtrauma text,
highriskchildneonatalsepsis text,
kunjunganneonatal text,
jenispelayanan text,
submissiondate text,
komplikasineonatallain text,
desaanak text,
tanggalkunjunganbayiperbulan text,
highriskchildcongenitalabnormality text,
existinglocation text,
frekuensinapas text,
highriskchildhypothermia text,
beratbayi text,
kondisibayi text,
registrationdate text,
komplikasineonatal text,
komplikasineonataltertangani text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.tambah_bayi (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		generatednotename14 text,
kecamatan text,
generatednotename13 text,
kabupaten text,
desa text,
today text,
district text,
sub_district text,
cityvillage text,
address1 text,
existinglocation text,
dusun text,
lokasiperiksaother text,
deviceid text,
instanceid text,
tanggalpendaftaran text,
phonenumber text,
province text,
provinsi text,
tanggalperiksa text,
lokasiperiksa text,
simserial text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.register_bayi_oa (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		submissiondate text,
uniqueid text,
sub_village text,
provinsi text,
nobayi text,
beratlahir text,
highrisklowbirthweight text,
province text,
district text,
desa text,
dusun text,
namabayi text,
jeniskelamin text,
highriskpregnancyyoungmaternalage text,
highriskpregnancyoldmaternalage text,
village text,
kabupaten text,
kecamatan text,
namasuami text,
tanggallahiranak text,
registrationdate text,
sub_district text,
noibu text,
namalengkap text,
alamatdomisili text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.penutupan_kb (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		keterangando text,
deathdate text,
submissiondate text,
registrationdate text,
jeniskontrasepsi text,
cityvillage text,
address1 text,
kbclosereason text,
keterangangagal text,
iskbcloseconfirmed text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.tambah_kb (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		kecamatan text,
alkihb text,
jeniskontrasepsi text,
existinglocation text,
sub_district text,
tanggalperiksa text,
lokasiperiksaother text,
keterangantentangpesertakb text,
umur text,
tdsistolik text,
namalengkap text,
dusun text,
alkilila text,
kabupaten text,
desa text,
tanggallahir text,
tddiastolik text,
paritas text,
address1 text,
district text,
tanggalkunjungan text,
lokasiperiksa text,
submissiondate text,
registrationdate text,
cityvillage text,
province text,
provinsi text,
alkipenyakitkronis text,
alkipenyakitims text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.edit_tambah_kb (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		address1 text,
paritas text,
alkipenyakitkronis text,
province text,
sub_district text,
dusun text,
kabupaten text,
lokasiperiksaother text,
existinglocation text,
alkipenyakitims text,
keterangantentangpesertakb text,
jeniskontrasepsi text,
tddiastolik text,
registrationdate text,
submissiondate text,
lokasiperiksa text,
kecamatan text,
tanggalkunjungan text,
umur text,
alkilila text,
namalengkap text,
provinsi text,
desa text,
tanggallahir text,
alkihb text,
cityvillage text,
tanggalperiksa text,
tdsistolik text,
district text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.tambah_kb_oa (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		ishighrisk text,
tanggalkunjungan text,
asuransijiwa text,
golongandarah text,
nomortelponhp text,
alkipenyakitkronis text,
village text,
tanggallahir text,
puskesmas text,
namalengkap text,
namasuami text,
posyandu text,
highrisknote text,
province text,
kecamatan text,
alamatdomisili text,
lokasiperiksa text,
provinsi text,
kabupaten text,
noibu text,
umur text,
pekerjaan text,
sub_district text,
sub_village text,
alkipenyakitims text,
keterangantentangpesertakb text,
alkilila text,
nik text,
gakintidak text,
pendidikan text,
namakader text,
namadukun text,
pptest text,
tdsistolik text,
tddiastolik text,
district text,
uniqueid text,
tooyoungrisk text,
toooldmother text,
submissiondate text,
paritas text,
jeniskontrasepsi text,
agama text,
alkihb text,
registrationdate text,
desa text,
dusun text);
---------------------------------------
CREATE TABLE IF NOT EXISTS sid3.kohort_pelayanan_kb (
		first_name character varying(75),
		last_name character varying(75),
		birth_date character varying(75),

		event_id character varying(75) UNIQUE,
		document_id character varying(75),
		base_entity_id character varying(75),
		location_id character varying(75),

		date_created timestamp without time zone,
		event_date timestamp without time zone,
		clientVersionSubmissionDate timestamp with time zone,
		serverVersionSubmissionDate timestamp with time zone,

		provider_id character varying(75),
		jeniskontrasepsi text,
keteranganganticara text,
keterangankomplikasi text,
submissiondate text,
cityvillage text,
existinglocation text,
tanggalkunjungan text,
keterangantentangpesertakb text,
registrationdate text,
address1 text,
lokasiperiksa text,
keterangantentangpesertakb2 text,
keteranganefeksamping text);
---------------------------------------
