-- DDL generated by Postico 1.4.4
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE sid3.child_registration (
    first_name character varying(75),
    last_name character varying(75),
    birth_date character varying(75),
    event_id character varying(75) UNIQUE,
    document_id character varying(75),
    base_entity_id character varying(75),
    location_id character varying(75),
    date_created timestamp without time zone,
    event_date timestamp without time zone,
    clientversionsubmissiondate timestamp with time zone,
    serverversionsubmissiondate timestamp with time zone,
    provider_id character varying(75),
    namabayi character varying(75),
    desaanak character varying(75),
    beratlahir character varying(75),
    highriskchildlowbirthweght character varying(75)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX child_registration_event_id_key ON sid3.child_registration(event_id text_ops);
